### ISSUE TITLE
Alternative services

### ISSUE THREAD

**Issue by mbriney** [bbernstein/homebridge-snowswitch#1]
With the Weather Underground API moving to a closed paid model (https://www.wunderground.com/weather/api/)  any thoughts on moving to a different provider?

**Comment by bbernstein** [comment]
I hadn't heard that, but winter is coming and I'll try to find a solution before the first snow. Thanks for the heads-up... any suggestions?

**Comment by bbernstein** [comment]
I hope they have a solution before they shut it down according to this:

- For developers who use WU API data for non-commercial purposes, you will have access to a new plan for a personal use, low call volume API. Stay tuned for more details as we build this out.

**Comment by bbernstein** [comment]
Looking at [OpenWeatherMap](https://openweathermap.org/) as a possibility.
Another to consider is [Accuweather Developer](https://developer.accuweather.com/).

**Comment by mbriney** [comment]
Would something like the Dark Sky API work?
https://darksky.net/dev

The first 1,000 API requests you make every day are free of charge

The forecast API returns current conditions
https://darksky.net/dev/docs#forecast-request

**Comment by bbernstein** [comment]
That looks good, and easier to get a key. Thanks, I'll see if I can do some work on it this weekend.

**Comment by bbernstein** [comment]
I finally had some time to work on this. I have a new version that I'll release soon using darksky. I'm making a few other improvements along the way so I'll bump the version number with the next release.

**Comment by bbernstein** [comment]
Updated to now use DarkSky instead of Weather Underground. Please upgrade and follow new directions for configuration. It will now use Lat/Lon rather than other location values. Also, you'll need a DarkSky API key.

Read the new instructions.
