### ISSUE TITLE
Occupancy Sensor

### ISSUE THREAD

**Issue by rmkjr** [bbernstein/homebridge-snowswitch#4]
I think this would work better if it presented itself as an occupancy senor.  This would still allow it to be used as a binary condition in automations, but would prevent you from accidentally turning on the switch in the home app by tapping it.

**Comment by bbernstein** [comment]
Good point. I was thinking of something along those lines recently since adding a motion sensor device and seeing how that works.  I thought also would be nice to get an optional notification when it goes on and off which seems part of what sensors do.

**Comment by bbernstein** [comment]
Much easier than I expected. Just a few simple changes and it seems like it will work as a sensor. 
I will need to test more, but I now have it in branch 'occ-sensor' in case you want to give it a try.

**Comment by bbernstein** [comment]
Pro: It now is a "sensor" which indicates that something was "detected". Also, a user can't change the state manually.
Con: The Home App says "Occupancy Detected", which is not really the right meaning. I imagine it would be impractical to make the app display "Snow Detected" since they are probably translation strings associated with the Service ID.

**Comment by bbernstein** [comment]
Another Pro: It now allows for Notifications. So I can be proactively alerted when it turns on.

**Comment by rmkjr** [comment]
Very cool stuff.  Going to give it a try later on today when I get home.  I’ve seen other plugins as well with the occupancy detected thing.  I assumed it’s something HomeKit side that couldn’t be changed.  That said, what I have usually done is just turn off the status message for those sensors, and then name the sensor (like yours defaults to IsSnowy).  That way it doesn’t show occupancy detected on the main home screen, but if I look at the sensor on the room page it will be light up.

**Comment by bbernstein** [comment]
No snow in my forecast so I'm pretending to be in Duluth today to make sure it's working. Let me know what you think when you've given it a try.

**Comment by bbernstein** [comment]
If it's no longer going to be a switch, I'll want to rename it SnowSense since which is will make for more interesting puns. I may also add some more sensors in case someone cares about recent or upcoming snow:

1. IsSnowing (is snowing now)
2. WasSnowing (has snowed recently)
3. WillSnow (will snow soon)
4. IsSnowy (what we have now: any of the above)

may not get that done today but I did make a new repo to start.

**Comment by rmkjr** [comment]
Had a chance to try out the sensor branch.  Did the same using a different location to test it out.  All looked good from this side and I definitely think the sensor makes more sense.

Great name idea.

I also like the additional sensors idea.  It seems like # 4 would be all in one configuration, where it uses the before and after options to broaden the time it is triggered.  Then # 1-3 would be used in concert instead of # 4.  Where # 2 and # 3 would have an after (for # 2) and before (for # 3) option to add some buffer to them, and then # 1 would be the current state.  Then for automations you could use the 3 sensors to be more granular, like doing things X hours before it snow, doing something else when it snows, and then something else for X hours after the snow stops.  The [homebridge-plex-sensors](https://github.com/alexp2ad/homebridge-plex-sensors#example-configs) plugin has a pretty good configuration method for handling multiple optional sensors with different config options for each by using an array to describe all the optional sensors.

Keep up the good work.  Looking forward to seeing how it progresses.

**Comment by bbernstein** [comment]
Set up new project [homebridge-snowsense](https://github.com/bbernstein/homebridge-snowsense) to create a new sensor-based version of this.

I didn't make a sophisticated sensor configuration like homebridge-plex-sensors, but if I have some time I may do that. For now, it simply takes a comma-delimited string of sensors. It's all documented in the project.

It's running for me now, but will be watching it to see if it's doing the right thing when snow comes and goes.

Closing this thread so feel free to start new issues in the new project.
