### ISSUE TITLE
Darksky no longer accepting new sign ups/shutting down

### ISSUE THREAD

**Issue by thewolfanator** [bbernstein/homebridge-snowswitch#7]
Hi there,

Thank so much for this plugin - this is exactly what I was looking for!  I just got HeatTrak Matts and this is perfect.  Seems straight forward and perfect for what I need.

PROBLEM: Darksky is no longer accepting new sign ups and will be shutting down in a few months.

Any suggestions on what to do to get this working?

thanks in advance!

**Comment by bbernstein** [comment]
I'm happy to help get things working with the HeatTrak mats. It's still working well for me.

I just added a message to the ReadMe. I've made a newer plugin that works slightly differently and supports OpenWeatherMap. Please use that plugin [SnowSense](https://github.com/bbernstein/homebridge-snowsense) going forward.

**Comment by thewolfanator** [comment]
Yes just found that one!  Thanks for the quick reply!  I have it all set up so just have to wait for some snow now. :-)

**Comment by thewolfanator** [comment]
thanks again for your work on this!

**Comment by thewolfanator** [comment]
So, it is currently snowing but the matts didn't turn on?  Not sure exactly how to figure out what I did wrong?

**Comment by bbernstein** [comment]
Join us over on [issue 14 of homebridge-snonwsense](https://github.com/bbernstein/homebridge-snowsense/issues/14) and we can work on it together.

**Comment by bbernstein** [comment]
closing this issue as this plugin isn't supported. Check out [homebridge-snowsense](https://github.com/bbernstein/homebridge-snowsense/) going forward
